---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  username: <%= ENV["winrm_user"] %>
  password: <%= ENV["winrm_pass"] %>
  port: <%= ENV["winrm_port"] %>

verifier:
  name: inspec

provisioner:
  name: shell

suites:
  - name: default
