---
driver:
  name: vagrant
  gui: false
  linked_clone: true

platforms:
  - name: ansibleserver
    driver_plugin: docker
    driver_config:
      image: rndmh3ro/docker-centos7-ansible:latest
      platform: centos
      network:
      - [ 'private_network', { ip: '172.28.128.10' } ]
    transport:
      max_ssh_sessions: 1
    provisioner:
      name: ansible_playbook
      roles_path: ../ansible-windows-hardening
      #role_name: kitchen_test_role
      ansible_connection: winrm
      ansible_inventory: hosts
      require_windows_support: true
      require_chef_for_busser: false
      ansible_host_key_checking: false
      ansible_verbose: false
      ansible_verbosity: 4
      playbook: default.yml
    verifier:
      name: shell
      command: exit 0

  - name: windows-2012R2
    driver_config:
      box: MattHodge/Windows2012R2Core-WMF5-NOCM
      communicator: winrm
      network:
      - [ 'private_network', { ip: '172.28.128.11' } ]
       # needed to force provision of the vagrantfile
      provision: true
      # needed to run the ConfigureRemotingForAnsible.ps1
      vagrantfiles:
        - vagrant_windows_target.rb
    transport:
      name: winrm
    verifier:
      name: inspec
    provisioner:
      name: shell

suites:
  - name: default
